#---------------------------------#
#      general configuration      #
#---------------------------------#

environment:
  nuget_api_key:
    secure: oy2j3an723gldzodlt5qaup2s3x2dleevoyh6c7jful5nu

# version format
version: 1.0.1{build}

# clone directory
clone_folder: C:\Users\AKa\Documents\GitHub\VL.FastNoise

branches:
  only:
    - master

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.1.{build}"
  assembly_file_version: "{version}"


install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - nuget pack appveyor\VL.FastNoise.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - nuget setApiKey %nuget_api_key%
  - nuget push C:\projects\VL.FastNoise\VL.FastNoise.%APPVEYOR_BUILD_VERSION%.nupkg -Source https://api.nuget.org/v3/index.json
    
artifacts:
  - path: '*.nupkg'
    type: NuGetPackage
  
#---------------------------------#
#         notifications           #
#---------------------------------#