#---------------------------------#
#      general configuration      #
#---------------------------------#

environment:
  nuget_api_key:
    secure: oy2brqsnha4kjvpmfauab3rl4n5fctkejfluw2tz3etlji

# version format
version: 1.0.{build}

# clone directory
clone_folder: c:\projects\VL.FastNoise

branches:
  only:
    - master

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.1.{build}-alpha"
  assembly_file_version: "{version}"


install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - nuget pack appveyor\VL.FastNoise.nuspec -Version %APPVEYOR_BUILD_VERSION%-alpha
  - nuget setApiKey %nuget_api_key%
  - nuget push C:\projects\VL.FastNoise\VL.FastNoise.%APPVEYOR_BUILD_VERSION%-alpha.nupkg -Source https://api.nuget.org/v3/index.json
    
artifacts:
  - path: '*.nupkg'
    type: NuGetPackage
  
#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:
- provider: Email 
to: 
- artrevinho@gmail.com 
subject: 'VL.FastNoise Build  
 message: "{{message}}, {{commitId}}, ..." 
on_build_status_changed: true
